version: "3.8"

name: em-backend

services:
  app:
    container_name: api
    build: .
    depends_on:
      - db
    ports:
      - ${APP_PORT}:3000
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - backend

  db:
    container_name: pg-db
    image: postgres:17.5-alpine
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - backend

volumes:
  db-data:
    labels:
      - "./database/postgres-data"

networks:
  backend: