version: "3.8"

name: em-backend

services:
  app:
    container_name: api
    build: .
    depends_on:
      - db
    ports:
      - ${APP_PORT}:3000
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - backend

  db:
    container_name: pg-db
    image: postgres:17.5-alpine
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - backend
#
#  api-specs:
#    container_name: api-specs-ui
#    image: swaggerapi/swagger-ui:v5.17.14
#    environment:
#      SWAGGER_JSON: /swagger/openapi.yaml
#    ports:
#      - "${SPECS_PORT}:8080"
#    volumes:
#      - ./swagger:/specs
#    depends_on:
#      - app

volumes:
  db-data:
    labels:
      - "./database/postgres-data"

networks:
  backend: